version: 2
updates:
  - package-ecosystem: "bun"
    directories: [ "/" ]
    schedule:
      interval: "weekly"
    assignees:
      - "theqeeqez"
      - "muhtoyyib"
    groups:
      dependencies:
        patterns:
          - "*"